# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from m3.snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


def write_to_Resource(
    proto_serializer: ProtoSerializer,
    attributes: List[MessageMarshaler] = None,
    dropped_attributes_count: int = 0,
):
    if dropped_attributes_count:
        proto_serializer.serialize_uint32(b"\x10", dropped_attributes_count)
    if attributes:
        proto_serializer.serialize_repeated_message(b"\n", attributes)
