# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import (
    Any,
    Dict,
    List,
    Optional,
)

from m5.snowflake.telemetry.serialize import (
    Enum,
    ProtoSerializer,
    util,
)


def ExportMetricsServiceRequest(
    resource_metrics: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    size = 0
    if resource_metrics:
        size += util.size_repeated_message(b"\n", resource_metrics)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportMetricsServiceRequest,
        "resource_metrics": resource_metrics,
    }


def write_to_ExportMetricsServiceRequest(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["resource_metrics"]:
        proto_serializer.serialize_repeated_message(b"\n", message["resource_metrics"])


def ExportMetricsServiceResponse(
    partial_success: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    size = 0
    if partial_success:
        size += util.size_message(b"\n", partial_success)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportMetricsServiceResponse,
        "partial_success": partial_success,
    }


def write_to_ExportMetricsServiceResponse(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["partial_success"]:
        proto_serializer.serialize_message(b"\n", message["partial_success"])


def ExportMetricsPartialSuccess(
    rejected_data_points: Optional[int] = None,
    error_message: Optional[str] = None,
) -> Dict[str, Any]:
    size = 0
    if rejected_data_points:
        size += util.size_int64(b"\x08", rejected_data_points)
    if error_message:
        size += util.size_string(b"\x12", error_message)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportMetricsPartialSuccess,
        "rejected_data_points": rejected_data_points,
        "error_message": error_message,
    }


def write_to_ExportMetricsPartialSuccess(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["rejected_data_points"]:
        proto_serializer.serialize_int64(b"\x08", message["rejected_data_points"])
    if message["error_message"]:
        proto_serializer.serialize_string(b"\x12", message["error_message"])
