# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/collector/logs/v1/logs_service.proto

from __future__ import annotations

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.logs.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class ExportLogsServiceRequest(MessageMarshaler):
    def __init__(
        self,
        resource_logs: List[ResourceLogs] = None,
    ):
        self.resource_logs: List[ResourceLogs] = resource_logs
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.resource_logs:
            size += util.size_repeated_message(b"\n", self.resource_logs)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.resource_logs:
            proto_serializer.serialize_repeated_message(b"\n", self.resource_logs)


class ExportLogsServiceResponse(MessageMarshaler):
    def __init__(
        self,
        partial_success: ExportLogsPartialSuccess = None,
    ):
        self.partial_success: ExportLogsPartialSuccess = partial_success
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.partial_success is not None:
            size += util.size_message(b"\n", self.partial_success)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.partial_success is not None:
            proto_serializer.serialize_message(b"\n", self.partial_success)


class ExportLogsPartialSuccess(MessageMarshaler):
    def __init__(
        self,
        rejected_log_records: int = 0,
        error_message: str = "",
    ):
        self.rejected_log_records: int = rejected_log_records
        self.error_message: str = error_message
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.rejected_log_records:
            size += util.size_int64(b"\x08", self.rejected_log_records)
        if self.error_message:
            size += util.size_string(b"\x12", self.error_message)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.rejected_log_records:
            proto_serializer.serialize_int64(b"\x08", self.rejected_log_records)
        if self.error_message:
            proto_serializer.serialize_string(b"\x12", self.error_message)
