# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/collector/logs/v1/logs_service.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.logs.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class ExportLogsServiceRequest(MessageMarshaler):
    resource_logs: List["ResourceLogs"]

    def __init__(
        self,
        resource_logs=None,
    ):
        self._resource_logs = resource_logs
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._resource_logs:
            __size += util.size_repeated_message(b"\n", self._resource_logs)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._resource_logs:
            proto_serializer.serialize_repeated_message(b"\n", self._resource_logs)


class ExportLogsServiceResponse(MessageMarshaler):
    partial_success: "ExportLogsPartialSuccess"

    def __init__(
        self,
        partial_success=None,
    ):
        self._partial_success = partial_success
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._partial_success is not None:
            __size += util.size_message(b"\n", self._partial_success)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._partial_success is not None:
            proto_serializer.serialize_message(b"\n", self._partial_success)


class ExportLogsPartialSuccess(MessageMarshaler):
    rejected_log_records: int
    error_message: str

    def __init__(
        self,
        rejected_log_records=0,
        error_message="",
    ):
        self.rejected_log_records = rejected_log_records
        self.error_message = error_message
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self.rejected_log_records:
            __size += util.size_int64(b"\x08", self.rejected_log_records)
        if self.error_message:
            __size += util.size_string(b"\x12", self.error_message)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.rejected_log_records:
            proto_serializer.serialize_int64(b"\x08", self.rejected_log_records)
        if self.error_message:
            proto_serializer.serialize_string(b"\x12", self.error_message)
