# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import (
    Any,
    Dict,
    List,
    Optional,
    TypedDict,
)

from m4.snowflake.telemetry.serialize import (
    Enum,
    ProtoSerializer,
    util,
)


def ExportLogsServiceRequest(
    resource_logs: Optional[List[bytes]] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if resource_logs:
        proto_serializer.serialize_repeated_message(b"\n", resource_logs)
    return proto_serializer.out


def ExportLogsServiceResponse(
    partial_success: Optional[bytes] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if partial_success:
        proto_serializer.serialize_message(b"\n", partial_success)
    return proto_serializer.out


def ExportLogsPartialSuccess(
    rejected_log_records: Optional[int] = None,
    error_message: Optional[str] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if rejected_log_records:
        proto_serializer.serialize_int64(b"\x08", rejected_log_records)
    if error_message:
        proto_serializer.serialize_string(b"\x12", error_message)
    return proto_serializer.out
