# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class Resource(MessageMarshaler):
    def __init__(
        self,
        attributes: List[MessageMarshaler] = None,
        dropped_attributes_count: int = 0,
    ):
        self.attributes = attributes
        self.dropped_attributes_count = dropped_attributes_count

        size = 0
        if attributes:
            size += util.size_repeated_message(b"\n", attributes)
        if dropped_attributes_count:
            size += util.size_uint32(b"\x10", dropped_attributes_count)

        super().__init__(size)

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.attributes:
            proto_serializer.serialize_repeated_message(b"\n", self.attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"\x10", self.dropped_attributes_count)
