# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


def write_to_ExportLogsServiceRequest(
    proto_serializer: ProtoSerializer,
    resource_logs: List[MessageMarshaler] = None,
):
    if resource_logs:
        proto_serializer.serialize_repeated_message(b"\n", resource_logs)


def write_to_ExportLogsServiceResponse(
    proto_serializer: ProtoSerializer,
    partial_success: MessageMarshaler = None,
):
    if partial_success:
        proto_serializer.serialize_message(b"\n", partial_success)


def write_to_ExportLogsPartialSuccess(
    proto_serializer: ProtoSerializer,
    rejected_log_records: int = 0,
    error_message: str = "",
):
    if error_message:
        proto_serializer.serialize_string(b"\x12", error_message)
    if rejected_log_records:
        proto_serializer.serialize_int64(b"\x08", rejected_log_records)
