# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/collector/metrics/v1/metrics_service.proto

from __future__ import annotations

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.metrics.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class ExportMetricsServiceRequest(MessageMarshaler):
    def __init__(
        self,
        resource_metrics: List[ResourceMetrics] = None,
    ):
        self.resource_metrics: List[ResourceMetrics] = resource_metrics
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.resource_metrics:
            size += util.size_repeated_message(b"\n", self.resource_metrics)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.resource_metrics:
            proto_serializer.serialize_repeated_message(b"\n", self.resource_metrics)


class ExportMetricsServiceResponse(MessageMarshaler):
    def __init__(
        self,
        partial_success: ExportMetricsPartialSuccess = None,
    ):
        self.partial_success: ExportMetricsPartialSuccess = partial_success
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.partial_success is not None:
            size += util.size_message(b"\n", self.partial_success)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.partial_success is not None:
            proto_serializer.serialize_message(b"\n", self.partial_success)


class ExportMetricsPartialSuccess(MessageMarshaler):
    def __init__(
        self,
        rejected_data_points: int = 0,
        error_message: str = "",
    ):
        self.rejected_data_points: int = rejected_data_points
        self.error_message: str = error_message
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.rejected_data_points:
            size += util.size_int64(b"\x08", self.rejected_data_points)
        if self.error_message:
            size += util.size_string(b"\x12", self.error_message)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.rejected_data_points:
            proto_serializer.serialize_int64(b"\x08", self.rejected_data_points)
        if self.error_message:
            proto_serializer.serialize_string(b"\x12", self.error_message)
