# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from m3.snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


class SeverityNumber(Enum):
    SEVERITY_NUMBER_UNSPECIFIED = 0
    SEVERITY_NUMBER_TRACE = 1
    SEVERITY_NUMBER_TRACE2 = 2
    SEVERITY_NUMBER_TRACE3 = 3
    SEVERITY_NUMBER_TRACE4 = 4
    SEVERITY_NUMBER_DEBUG = 5
    SEVERITY_NUMBER_DEBUG2 = 6
    SEVERITY_NUMBER_DEBUG3 = 7
    SEVERITY_NUMBER_DEBUG4 = 8
    SEVERITY_NUMBER_INFO = 9
    SEVERITY_NUMBER_INFO2 = 10
    SEVERITY_NUMBER_INFO3 = 11
    SEVERITY_NUMBER_INFO4 = 12
    SEVERITY_NUMBER_WARN = 13
    SEVERITY_NUMBER_WARN2 = 14
    SEVERITY_NUMBER_WARN3 = 15
    SEVERITY_NUMBER_WARN4 = 16
    SEVERITY_NUMBER_ERROR = 17
    SEVERITY_NUMBER_ERROR2 = 18
    SEVERITY_NUMBER_ERROR3 = 19
    SEVERITY_NUMBER_ERROR4 = 20
    SEVERITY_NUMBER_FATAL = 21
    SEVERITY_NUMBER_FATAL2 = 22
    SEVERITY_NUMBER_FATAL3 = 23
    SEVERITY_NUMBER_FATAL4 = 24


class LogRecordFlags(Enum):
    LOG_RECORD_FLAGS_DO_NOT_USE = 0
    LOG_RECORD_FLAGS_TRACE_FLAGS_MASK = 255


def write_to_LogsData(
    proto_serializer: ProtoSerializer,
    resource_logs: List[MessageMarshaler] = None,
):
    if resource_logs:
        proto_serializer.serialize_repeated_message(b"\n", resource_logs)


def write_to_ResourceLogs(
    proto_serializer: ProtoSerializer,
    resource: MessageMarshaler = None,
    scope_logs: List[MessageMarshaler] = None,
    schema_url: str = "",
):
    if schema_url:
        proto_serializer.serialize_string(b"\x1a", schema_url)
    if scope_logs:
        proto_serializer.serialize_repeated_message(b"\x12", scope_logs)
    if resource:
        proto_serializer.serialize_message(b"\n", resource)


def write_to_ScopeLogs(
    proto_serializer: ProtoSerializer,
    scope: MessageMarshaler = None,
    log_records: List[MessageMarshaler] = None,
    schema_url: str = "",
):
    if schema_url:
        proto_serializer.serialize_string(b"\x1a", schema_url)
    if log_records:
        proto_serializer.serialize_repeated_message(b"\x12", log_records)
    if scope:
        proto_serializer.serialize_message(b"\n", scope)


def write_to_LogRecord(
    proto_serializer: ProtoSerializer,
    time_unix_nano: int = 0,
    severity_number: int = 0,
    severity_text: str = "",
    body: MessageMarshaler = None,
    attributes: List[MessageMarshaler] = None,
    dropped_attributes_count: int = 0,
    flags: int = 0,
    trace_id: bytes = b"",
    span_id: bytes = b"",
    observed_time_unix_nano: int = 0,
):
    if observed_time_unix_nano:
        proto_serializer.serialize_fixed64(b"Y", observed_time_unix_nano)
    if span_id:
        proto_serializer.serialize_bytes(b"R", span_id)
    if trace_id:
        proto_serializer.serialize_bytes(b"J", trace_id)
    if flags:
        proto_serializer.serialize_fixed32(b"E", flags)
    if dropped_attributes_count:
        proto_serializer.serialize_uint32(b"8", dropped_attributes_count)
    if attributes:
        proto_serializer.serialize_repeated_message(b"2", attributes)
    if body:
        proto_serializer.serialize_message(b"*", body)
    if severity_text:
        proto_serializer.serialize_string(b"\x1a", severity_text)
    if severity_number:
        proto_serializer.serialize_enum(b"\x10", severity_number)
    if time_unix_nano:
        proto_serializer.serialize_fixed64(b"\t", time_unix_nano)
