# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from m3.snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


def write_to_ExportTraceServiceRequest(
    proto_serializer: ProtoSerializer,
    resource_spans: List[MessageMarshaler] = None,
):
    if resource_spans:
        proto_serializer.serialize_repeated_message(b"\n", resource_spans)


def write_to_ExportTraceServiceResponse(
    proto_serializer: ProtoSerializer,
    partial_success: MessageMarshaler = None,
):
    if partial_success:
        proto_serializer.serialize_message(b"\n", partial_success)


def write_to_ExportTracePartialSuccess(
    proto_serializer: ProtoSerializer,
    rejected_spans: int = 0,
    error_message: str = "",
):
    if error_message:
        proto_serializer.serialize_string(b"\x12", error_message)
    if rejected_spans:
        proto_serializer.serialize_int64(b"\x08", rejected_spans)
