# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/logs/v1/logs.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.opentelemetry.proto.resource.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class SeverityNumber(Enum):
    SEVERITY_NUMBER_UNSPECIFIED = 0
    SEVERITY_NUMBER_TRACE = 1
    SEVERITY_NUMBER_TRACE2 = 2
    SEVERITY_NUMBER_TRACE3 = 3
    SEVERITY_NUMBER_TRACE4 = 4
    SEVERITY_NUMBER_DEBUG = 5
    SEVERITY_NUMBER_DEBUG2 = 6
    SEVERITY_NUMBER_DEBUG3 = 7
    SEVERITY_NUMBER_DEBUG4 = 8
    SEVERITY_NUMBER_INFO = 9
    SEVERITY_NUMBER_INFO2 = 10
    SEVERITY_NUMBER_INFO3 = 11
    SEVERITY_NUMBER_INFO4 = 12
    SEVERITY_NUMBER_WARN = 13
    SEVERITY_NUMBER_WARN2 = 14
    SEVERITY_NUMBER_WARN3 = 15
    SEVERITY_NUMBER_WARN4 = 16
    SEVERITY_NUMBER_ERROR = 17
    SEVERITY_NUMBER_ERROR2 = 18
    SEVERITY_NUMBER_ERROR3 = 19
    SEVERITY_NUMBER_ERROR4 = 20
    SEVERITY_NUMBER_FATAL = 21
    SEVERITY_NUMBER_FATAL2 = 22
    SEVERITY_NUMBER_FATAL3 = 23
    SEVERITY_NUMBER_FATAL4 = 24


class LogRecordFlags(Enum):
    LOG_RECORD_FLAGS_DO_NOT_USE = 0
    LOG_RECORD_FLAGS_TRACE_FLAGS_MASK = 255


class LogsData(MessageMarshaler):
    resource_logs: List["ResourceLogs"]

    def __init__(
        self,
        resource_logs=None,
    ):
        self._resource_logs = resource_logs
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._resource_logs:
            __size += util.size_repeated_message(b"\n", self._resource_logs)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._resource_logs:
            proto_serializer.serialize_repeated_message(b"\n", self._resource_logs)


class ResourceLogs(MessageMarshaler):
    resource: "Resource"
    scope_logs: List["ScopeLogs"]
    schema_url: str

    def __init__(
        self,
        resource=None,
        scope_logs=None,
        schema_url="",
    ):
        self._resource = resource
        self._scope_logs = scope_logs
        self.schema_url = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._resource is not None:
            __size += util.size_message(b"\n", self._resource)
        if self._scope_logs:
            __size += util.size_repeated_message(b"\x12", self._scope_logs)
        if self.schema_url:
            __size += util.size_string(b"\x1a", self.schema_url)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._resource is not None:
            proto_serializer.serialize_message(b"\n", self._resource)
        if self._scope_logs:
            proto_serializer.serialize_repeated_message(b"\x12", self._scope_logs)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class ScopeLogs(MessageMarshaler):
    scope: "InstrumentationScope"
    log_records: List["LogRecord"]
    schema_url: str

    def __init__(
        self,
        scope=None,
        log_records=None,
        schema_url="",
    ):
        self._scope = scope
        self._log_records = log_records
        self.schema_url = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._scope is not None:
            __size += util.size_message(b"\n", self._scope)
        if self._log_records:
            __size += util.size_repeated_message(b"\x12", self._log_records)
        if self.schema_url:
            __size += util.size_string(b"\x1a", self.schema_url)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._scope is not None:
            proto_serializer.serialize_message(b"\n", self._scope)
        if self._log_records:
            proto_serializer.serialize_repeated_message(b"\x12", self._log_records)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class LogRecord(MessageMarshaler):
    time_unix_nano: int
    severity_number: int
    severity_text: str
    body: "AnyValue"
    attributes: List["KeyValue"]
    dropped_attributes_count: int
    flags: int
    trace_id: bytes
    span_id: bytes
    observed_time_unix_nano: int

    def __init__(
        self,
        time_unix_nano=0,
        severity_number=0,
        severity_text="",
        body=None,
        attributes=None,
        dropped_attributes_count=0,
        flags=0,
        trace_id=b"",
        span_id=b"",
        observed_time_unix_nano=0,
    ):
        self.time_unix_nano = time_unix_nano
        self.severity_number = severity_number
        self.severity_text = severity_text
        self._body = body
        self._attributes = attributes
        self.dropped_attributes_count = dropped_attributes_count
        self.flags = flags
        self.trace_id = trace_id
        self.span_id = span_id
        self.observed_time_unix_nano = observed_time_unix_nano
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self.time_unix_nano:
            __size += util.size_fixed64(b"\t", self.time_unix_nano)
        if self.severity_number:
            __size += util.size_enum(b"\x10", self.severity_number)
        if self.severity_text:
            __size += util.size_string(b"\x1a", self.severity_text)
        if self._body is not None:
            __size += util.size_message(b"*", self._body)
        if self._attributes:
            __size += util.size_repeated_message(b"2", self._attributes)
        if self.dropped_attributes_count:
            __size += util.size_uint32(b"8", self.dropped_attributes_count)
        if self.flags:
            __size += util.size_fixed32(b"E", self.flags)
        if self.trace_id:
            __size += util.size_bytes(b"J", self.trace_id)
        if self.span_id:
            __size += util.size_bytes(b"R", self.span_id)
        if self.observed_time_unix_nano:
            __size += util.size_fixed64(b"Y", self.observed_time_unix_nano)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.time_unix_nano:
            proto_serializer.serialize_fixed64(b"\t", self.time_unix_nano)
        if self.severity_number:
            proto_serializer.serialize_enum(b"\x10", self.severity_number)
        if self.severity_text:
            proto_serializer.serialize_string(b"\x1a", self.severity_text)
        if self._body is not None:
            proto_serializer.serialize_message(b"*", self._body)
        if self._attributes:
            proto_serializer.serialize_repeated_message(b"2", self._attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"8", self.dropped_attributes_count)
        if self.flags:
            proto_serializer.serialize_fixed32(b"E", self.flags)
        if self.trace_id:
            proto_serializer.serialize_bytes(b"J", self.trace_id)
        if self.span_id:
            proto_serializer.serialize_bytes(b"R", self.span_id)
        if self.observed_time_unix_nano:
            proto_serializer.serialize_fixed64(b"Y", self.observed_time_unix_nano)
