# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from m3.snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


def write_to_ExportMetricsServiceRequest(
    proto_serializer: ProtoSerializer,
    resource_metrics: List[MessageMarshaler] = None,
):
    if resource_metrics:
        proto_serializer.serialize_repeated_message(b"\n", resource_metrics)


def write_to_ExportMetricsServiceResponse(
    proto_serializer: ProtoSerializer,
    partial_success: MessageMarshaler = None,
):
    if partial_success:
        proto_serializer.serialize_message(b"\n", partial_success)


def write_to_ExportMetricsPartialSuccess(
    proto_serializer: ProtoSerializer,
    rejected_data_points: int = 0,
    error_message: str = "",
):
    if error_message:
        proto_serializer.serialize_string(b"\x12", error_message)
    if rejected_data_points:
        proto_serializer.serialize_int64(b"\x08", rejected_data_points)
