# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import (
    Any,
    Dict,
    List,
    Optional,
)

from m5.snowflake.telemetry.serialize import (
    Enum,
    ProtoSerializer,
    util,
)


def ExportTraceServiceRequest(
    resource_spans: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    size = 0
    if resource_spans:
        size += util.size_repeated_message(b"\n", resource_spans)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportTraceServiceRequest,
        "resource_spans": resource_spans,
    }


def write_to_ExportTraceServiceRequest(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["resource_spans"]:
        proto_serializer.serialize_repeated_message(b"\n", message["resource_spans"])


def ExportTraceServiceResponse(
    partial_success: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    size = 0
    if partial_success:
        size += util.size_message(b"\n", partial_success)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportTraceServiceResponse,
        "partial_success": partial_success,
    }


def write_to_ExportTraceServiceResponse(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["partial_success"]:
        proto_serializer.serialize_message(b"\n", message["partial_success"])


def ExportTracePartialSuccess(
    rejected_spans: Optional[int] = None,
    error_message: Optional[str] = None,
) -> Dict[str, Any]:
    size = 0
    if rejected_spans:
        size += util.size_int64(b"\x08", rejected_spans)
    if error_message:
        size += util.size_string(b"\x12", error_message)

    return {
        "__size": size,
        "__serialize_function": write_to_ExportTracePartialSuccess,
        "rejected_spans": rejected_spans,
        "error_message": error_message,
    }


def write_to_ExportTracePartialSuccess(
    message: Dict[str, Any], proto_serializer: ProtoSerializer
) -> None:
    if message["rejected_spans"]:
        proto_serializer.serialize_int64(b"\x08", message["rejected_spans"])
    if message["error_message"]:
        proto_serializer.serialize_string(b"\x12", message["error_message"])
