# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/trace/v1/trace.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.opentelemetry.proto.resource.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class SpanFlags(Enum):
    SPAN_FLAGS_DO_NOT_USE = 0
    SPAN_FLAGS_TRACE_FLAGS_MASK = 255
    SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK = 256
    SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK = 512


class TracesData(MessageMarshaler):
    resource_spans: List["ResourceSpans"]

    def __init__(
        self,
        resource_spans=None,
    ):
        self._resource_spans = resource_spans
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._resource_spans:
            __size += util.size_repeated_message(b"\n", self._resource_spans)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._resource_spans:
            proto_serializer.serialize_repeated_message(b"\n", self._resource_spans)


class ResourceSpans(MessageMarshaler):
    resource: "Resource"
    scope_spans: List["ScopeSpans"]
    schema_url: str

    def __init__(
        self,
        resource=None,
        scope_spans=None,
        schema_url="",
    ):
        self._resource = resource
        self._scope_spans = scope_spans
        self.schema_url = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._resource is not None:
            __size += util.size_message(b"\n", self._resource)
        if self._scope_spans:
            __size += util.size_repeated_message(b"\x12", self._scope_spans)
        if self.schema_url:
            __size += util.size_string(b"\x1a", self.schema_url)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._resource is not None:
            proto_serializer.serialize_message(b"\n", self._resource)
        if self._scope_spans:
            proto_serializer.serialize_repeated_message(b"\x12", self._scope_spans)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class ScopeSpans(MessageMarshaler):
    scope: "InstrumentationScope"
    spans: List["Span"]
    schema_url: str

    def __init__(
        self,
        scope=None,
        spans=None,
        schema_url="",
    ):
        self._scope = scope
        self._spans = spans
        self.schema_url = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self._scope is not None:
            __size += util.size_message(b"\n", self._scope)
        if self._spans:
            __size += util.size_repeated_message(b"\x12", self._spans)
        if self.schema_url:
            __size += util.size_string(b"\x1a", self.schema_url)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._scope is not None:
            proto_serializer.serialize_message(b"\n", self._scope)
        if self._spans:
            proto_serializer.serialize_repeated_message(b"\x12", self._spans)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class Span(MessageMarshaler):
    trace_id: bytes
    span_id: bytes
    trace_state: str
    parent_span_id: bytes
    name: str
    kind: int
    start_time_unix_nano: int
    end_time_unix_nano: int
    attributes: List["KeyValue"]
    dropped_attributes_count: int
    events: List["Span.Event"]
    dropped_events_count: int
    links: List["Span.Link"]
    dropped_links_count: int
    status: "Status"
    flags: int

    def __init__(
        self,
        trace_id=b"",
        span_id=b"",
        trace_state="",
        parent_span_id=b"",
        name="",
        kind=0,
        start_time_unix_nano=0,
        end_time_unix_nano=0,
        attributes=None,
        dropped_attributes_count=0,
        events=None,
        dropped_events_count=0,
        links=None,
        dropped_links_count=0,
        status=None,
        flags=0,
    ):
        self.trace_id = trace_id
        self.span_id = span_id
        self.trace_state = trace_state
        self.parent_span_id = parent_span_id
        self.name = name
        self.kind = kind
        self.start_time_unix_nano = start_time_unix_nano
        self.end_time_unix_nano = end_time_unix_nano
        self._attributes = attributes
        self.dropped_attributes_count = dropped_attributes_count
        self._events = events
        self.dropped_events_count = dropped_events_count
        self._links = links
        self.dropped_links_count = dropped_links_count
        self._status = status
        self.flags = flags
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self.trace_id:
            __size += util.size_bytes(b"\n", self.trace_id)
        if self.span_id:
            __size += util.size_bytes(b"\x12", self.span_id)
        if self.trace_state:
            __size += util.size_string(b"\x1a", self.trace_state)
        if self.parent_span_id:
            __size += util.size_bytes(b'"', self.parent_span_id)
        if self.name:
            __size += util.size_string(b"*", self.name)
        if self.kind:
            __size += util.size_enum(b"0", self.kind)
        if self.start_time_unix_nano:
            __size += util.size_fixed64(b"9", self.start_time_unix_nano)
        if self.end_time_unix_nano:
            __size += util.size_fixed64(b"A", self.end_time_unix_nano)
        if self._attributes:
            __size += util.size_repeated_message(b"J", self._attributes)
        if self.dropped_attributes_count:
            __size += util.size_uint32(b"P", self.dropped_attributes_count)
        if self._events:
            __size += util.size_repeated_message(b"Z", self._events)
        if self.dropped_events_count:
            __size += util.size_uint32(b"`", self.dropped_events_count)
        if self._links:
            __size += util.size_repeated_message(b"j", self._links)
        if self.dropped_links_count:
            __size += util.size_uint32(b"p", self.dropped_links_count)
        if self._status is not None:
            __size += util.size_message(b"z", self._status)
        if self.flags:
            __size += util.size_fixed32(b"\x85\x01", self.flags)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.trace_id:
            proto_serializer.serialize_bytes(b"\n", self.trace_id)
        if self.span_id:
            proto_serializer.serialize_bytes(b"\x12", self.span_id)
        if self.trace_state:
            proto_serializer.serialize_string(b"\x1a", self.trace_state)
        if self.parent_span_id:
            proto_serializer.serialize_bytes(b'"', self.parent_span_id)
        if self.name:
            proto_serializer.serialize_string(b"*", self.name)
        if self.kind:
            proto_serializer.serialize_enum(b"0", self.kind)
        if self.start_time_unix_nano:
            proto_serializer.serialize_fixed64(b"9", self.start_time_unix_nano)
        if self.end_time_unix_nano:
            proto_serializer.serialize_fixed64(b"A", self.end_time_unix_nano)
        if self._attributes:
            proto_serializer.serialize_repeated_message(b"J", self._attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"P", self.dropped_attributes_count)
        if self._events:
            proto_serializer.serialize_repeated_message(b"Z", self._events)
        if self.dropped_events_count:
            proto_serializer.serialize_uint32(b"`", self.dropped_events_count)
        if self._links:
            proto_serializer.serialize_repeated_message(b"j", self._links)
        if self.dropped_links_count:
            proto_serializer.serialize_uint32(b"p", self.dropped_links_count)
        if self._status is not None:
            proto_serializer.serialize_message(b"z", self._status)
        if self.flags:
            proto_serializer.serialize_fixed32(b"\x85\x01", self.flags)

    class SpanKind(Enum):
        SPAN_KIND_UNSPECIFIED = 0
        SPAN_KIND_INTERNAL = 1
        SPAN_KIND_SERVER = 2
        SPAN_KIND_CLIENT = 3
        SPAN_KIND_PRODUCER = 4
        SPAN_KIND_CONSUMER = 5

    class Event(MessageMarshaler):
        time_unix_nano: int
        name: str
        attributes: List["KeyValue"]
        dropped_attributes_count: int

        def __init__(
            self,
            time_unix_nano=0,
            name="",
            attributes=None,
            dropped_attributes_count=0,
        ):
            self.time_unix_nano = time_unix_nano
            self.name = name
            self._attributes = attributes
            self.dropped_attributes_count = dropped_attributes_count
            super().__init__()

        def calculate_size(self) -> int:
            __size = 0
            if self.time_unix_nano:
                __size += util.size_fixed64(b"\t", self.time_unix_nano)
            if self.name:
                __size += util.size_string(b"\x12", self.name)
            if self._attributes:
                __size += util.size_repeated_message(b"\x1a", self._attributes)
            if self.dropped_attributes_count:
                __size += util.size_uint32(b" ", self.dropped_attributes_count)
            return __size

        def write_to(self, proto_serializer: ProtoSerializer) -> None:
            if self.time_unix_nano:
                proto_serializer.serialize_fixed64(b"\t", self.time_unix_nano)
            if self.name:
                proto_serializer.serialize_string(b"\x12", self.name)
            if self._attributes:
                proto_serializer.serialize_repeated_message(b"\x1a", self._attributes)
            if self.dropped_attributes_count:
                proto_serializer.serialize_uint32(b" ", self.dropped_attributes_count)

    class Link(MessageMarshaler):
        trace_id: bytes
        span_id: bytes
        trace_state: str
        attributes: List["KeyValue"]
        dropped_attributes_count: int
        flags: int

        def __init__(
            self,
            trace_id=b"",
            span_id=b"",
            trace_state="",
            attributes=None,
            dropped_attributes_count=0,
            flags=0,
        ):
            self.trace_id = trace_id
            self.span_id = span_id
            self.trace_state = trace_state
            self._attributes = attributes
            self.dropped_attributes_count = dropped_attributes_count
            self.flags = flags
            super().__init__()

        def calculate_size(self) -> int:
            __size = 0
            if self.trace_id:
                __size += util.size_bytes(b"\n", self.trace_id)
            if self.span_id:
                __size += util.size_bytes(b"\x12", self.span_id)
            if self.trace_state:
                __size += util.size_string(b"\x1a", self.trace_state)
            if self._attributes:
                __size += util.size_repeated_message(b'"', self._attributes)
            if self.dropped_attributes_count:
                __size += util.size_uint32(b"(", self.dropped_attributes_count)
            if self.flags:
                __size += util.size_fixed32(b"5", self.flags)
            return __size

        def write_to(self, proto_serializer: ProtoSerializer) -> None:
            if self.trace_id:
                proto_serializer.serialize_bytes(b"\n", self.trace_id)
            if self.span_id:
                proto_serializer.serialize_bytes(b"\x12", self.span_id)
            if self.trace_state:
                proto_serializer.serialize_string(b"\x1a", self.trace_state)
            if self._attributes:
                proto_serializer.serialize_repeated_message(b'"', self._attributes)
            if self.dropped_attributes_count:
                proto_serializer.serialize_uint32(b"(", self.dropped_attributes_count)
            if self.flags:
                proto_serializer.serialize_fixed32(b"5", self.flags)


class Status(MessageMarshaler):
    message: str
    code: int

    def __init__(
        self,
        message="",
        code=0,
    ):
        self.message = message
        self.code = code
        super().__init__()

    def calculate_size(self) -> int:
        __size = 0
        if self.message:
            __size += util.size_string(b"\x12", self.message)
        if self.code:
            __size += util.size_enum(b"\x18", self.code)
        return __size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.message:
            proto_serializer.serialize_string(b"\x12", self.message)
        if self.code:
            proto_serializer.serialize_enum(b"\x18", self.code)

    class StatusCode(Enum):
        STATUS_CODE_UNSET = 0
        STATUS_CODE_OK = 1
        STATUS_CODE_ERROR = 2
