# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/trace/v1/trace.proto

from __future__ import annotations

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.opentelemetry.proto.resource.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class SpanFlags(Enum):
    SPAN_FLAGS_DO_NOT_USE = 0
    SPAN_FLAGS_TRACE_FLAGS_MASK = 255
    SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK = 256
    SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK = 512


class TracesData(MessageMarshaler):
    def __init__(
        self,
        resource_spans: List[ResourceSpans] = None,
    ):
        self.resource_spans: List[ResourceSpans] = resource_spans
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.resource_spans:
            size += util.size_repeated_message(b"\n", self.resource_spans)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.resource_spans:
            proto_serializer.serialize_repeated_message(b"\n", self.resource_spans)


class ResourceSpans(MessageMarshaler):
    def __init__(
        self,
        resource: Resource = None,
        scope_spans: List[ScopeSpans] = None,
        schema_url: str = "",
    ):
        self.resource: Resource = resource
        self.scope_spans: List[ScopeSpans] = scope_spans
        self.schema_url: str = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.resource is not None:
            size += util.size_message(b"\n", self.resource)
        if self.scope_spans:
            size += util.size_repeated_message(b"\x12", self.scope_spans)
        if self.schema_url:
            size += util.size_string(b"\x1a", self.schema_url)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.resource is not None:
            proto_serializer.serialize_message(b"\n", self.resource)
        if self.scope_spans:
            proto_serializer.serialize_repeated_message(b"\x12", self.scope_spans)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class ScopeSpans(MessageMarshaler):
    def __init__(
        self,
        scope: InstrumentationScope = None,
        spans: List[Span] = None,
        schema_url: str = "",
    ):
        self.scope: InstrumentationScope = scope
        self.spans: List[Span] = spans
        self.schema_url: str = schema_url
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.scope is not None:
            size += util.size_message(b"\n", self.scope)
        if self.spans:
            size += util.size_repeated_message(b"\x12", self.spans)
        if self.schema_url:
            size += util.size_string(b"\x1a", self.schema_url)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.scope is not None:
            proto_serializer.serialize_message(b"\n", self.scope)
        if self.spans:
            proto_serializer.serialize_repeated_message(b"\x12", self.spans)
        if self.schema_url:
            proto_serializer.serialize_string(b"\x1a", self.schema_url)


class Span(MessageMarshaler):
    def __init__(
        self,
        trace_id: bytes = b"",
        span_id: bytes = b"",
        trace_state: str = "",
        parent_span_id: bytes = b"",
        name: str = "",
        kind: int = 0,
        start_time_unix_nano: int = 0,
        end_time_unix_nano: int = 0,
        attributes: List[KeyValue] = None,
        dropped_attributes_count: int = 0,
        events: List[Span.Event] = None,
        dropped_events_count: int = 0,
        links: List[Span.Link] = None,
        dropped_links_count: int = 0,
        status: Status = None,
        flags: int = 0,
    ):
        self.trace_id: bytes = trace_id
        self.span_id: bytes = span_id
        self.trace_state: str = trace_state
        self.parent_span_id: bytes = parent_span_id
        self.name: str = name
        self.kind: int = kind
        self.start_time_unix_nano: int = start_time_unix_nano
        self.end_time_unix_nano: int = end_time_unix_nano
        self.attributes: List[KeyValue] = attributes
        self.dropped_attributes_count: int = dropped_attributes_count
        self.events: List[Span.Event] = events
        self.dropped_events_count: int = dropped_events_count
        self.links: List[Span.Link] = links
        self.dropped_links_count: int = dropped_links_count
        self.status: Status = status
        self.flags: int = flags
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.trace_id:
            size += util.size_bytes(b"\n", self.trace_id)
        if self.span_id:
            size += util.size_bytes(b"\x12", self.span_id)
        if self.trace_state:
            size += util.size_string(b"\x1a", self.trace_state)
        if self.parent_span_id:
            size += util.size_bytes(b'"', self.parent_span_id)
        if self.name:
            size += util.size_string(b"*", self.name)
        if self.kind:
            size += util.size_enum(b"0", self.kind)
        if self.start_time_unix_nano:
            size += util.size_fixed64(b"9", self.start_time_unix_nano)
        if self.end_time_unix_nano:
            size += util.size_fixed64(b"A", self.end_time_unix_nano)
        if self.attributes:
            size += util.size_repeated_message(b"J", self.attributes)
        if self.dropped_attributes_count:
            size += util.size_uint32(b"P", self.dropped_attributes_count)
        if self.events:
            size += util.size_repeated_message(b"Z", self.events)
        if self.dropped_events_count:
            size += util.size_uint32(b"`", self.dropped_events_count)
        if self.links:
            size += util.size_repeated_message(b"j", self.links)
        if self.dropped_links_count:
            size += util.size_uint32(b"p", self.dropped_links_count)
        if self.status is not None:
            size += util.size_message(b"z", self.status)
        if self.flags:
            size += util.size_fixed32(b"\x85\x01", self.flags)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.trace_id:
            proto_serializer.serialize_bytes(b"\n", self.trace_id)
        if self.span_id:
            proto_serializer.serialize_bytes(b"\x12", self.span_id)
        if self.trace_state:
            proto_serializer.serialize_string(b"\x1a", self.trace_state)
        if self.parent_span_id:
            proto_serializer.serialize_bytes(b'"', self.parent_span_id)
        if self.name:
            proto_serializer.serialize_string(b"*", self.name)
        if self.kind:
            proto_serializer.serialize_enum(b"0", self.kind)
        if self.start_time_unix_nano:
            proto_serializer.serialize_fixed64(b"9", self.start_time_unix_nano)
        if self.end_time_unix_nano:
            proto_serializer.serialize_fixed64(b"A", self.end_time_unix_nano)
        if self.attributes:
            proto_serializer.serialize_repeated_message(b"J", self.attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"P", self.dropped_attributes_count)
        if self.events:
            proto_serializer.serialize_repeated_message(b"Z", self.events)
        if self.dropped_events_count:
            proto_serializer.serialize_uint32(b"`", self.dropped_events_count)
        if self.links:
            proto_serializer.serialize_repeated_message(b"j", self.links)
        if self.dropped_links_count:
            proto_serializer.serialize_uint32(b"p", self.dropped_links_count)
        if self.status is not None:
            proto_serializer.serialize_message(b"z", self.status)
        if self.flags:
            proto_serializer.serialize_fixed32(b"\x85\x01", self.flags)

    class SpanKind(Enum):
        SPAN_KIND_UNSPECIFIED = 0
        SPAN_KIND_INTERNAL = 1
        SPAN_KIND_SERVER = 2
        SPAN_KIND_CLIENT = 3
        SPAN_KIND_PRODUCER = 4
        SPAN_KIND_CONSUMER = 5

    class Event(MessageMarshaler):
        def __init__(
            self,
            time_unix_nano: int = 0,
            name: str = "",
            attributes: List[KeyValue] = None,
            dropped_attributes_count: int = 0,
        ):
            self.time_unix_nano: int = time_unix_nano
            self.name: str = name
            self.attributes: List[KeyValue] = attributes
            self.dropped_attributes_count: int = dropped_attributes_count
            super().__init__()

        def calculate_size(self) -> int:
            size = 0
            if self.time_unix_nano:
                size += util.size_fixed64(b"\t", self.time_unix_nano)
            if self.name:
                size += util.size_string(b"\x12", self.name)
            if self.attributes:
                size += util.size_repeated_message(b"\x1a", self.attributes)
            if self.dropped_attributes_count:
                size += util.size_uint32(b" ", self.dropped_attributes_count)
            return size

        def write_to(self, proto_serializer: ProtoSerializer) -> None:
            if self.time_unix_nano:
                proto_serializer.serialize_fixed64(b"\t", self.time_unix_nano)
            if self.name:
                proto_serializer.serialize_string(b"\x12", self.name)
            if self.attributes:
                proto_serializer.serialize_repeated_message(b"\x1a", self.attributes)
            if self.dropped_attributes_count:
                proto_serializer.serialize_uint32(b" ", self.dropped_attributes_count)

    class Link(MessageMarshaler):
        def __init__(
            self,
            trace_id: bytes = b"",
            span_id: bytes = b"",
            trace_state: str = "",
            attributes: List[KeyValue] = None,
            dropped_attributes_count: int = 0,
            flags: int = 0,
        ):
            self.trace_id: bytes = trace_id
            self.span_id: bytes = span_id
            self.trace_state: str = trace_state
            self.attributes: List[KeyValue] = attributes
            self.dropped_attributes_count: int = dropped_attributes_count
            self.flags: int = flags
            super().__init__()

        def calculate_size(self) -> int:
            size = 0
            if self.trace_id:
                size += util.size_bytes(b"\n", self.trace_id)
            if self.span_id:
                size += util.size_bytes(b"\x12", self.span_id)
            if self.trace_state:
                size += util.size_string(b"\x1a", self.trace_state)
            if self.attributes:
                size += util.size_repeated_message(b'"', self.attributes)
            if self.dropped_attributes_count:
                size += util.size_uint32(b"(", self.dropped_attributes_count)
            if self.flags:
                size += util.size_fixed32(b"5", self.flags)
            return size

        def write_to(self, proto_serializer: ProtoSerializer) -> None:
            if self.trace_id:
                proto_serializer.serialize_bytes(b"\n", self.trace_id)
            if self.span_id:
                proto_serializer.serialize_bytes(b"\x12", self.span_id)
            if self.trace_state:
                proto_serializer.serialize_string(b"\x1a", self.trace_state)
            if self.attributes:
                proto_serializer.serialize_repeated_message(b'"', self.attributes)
            if self.dropped_attributes_count:
                proto_serializer.serialize_uint32(b"(", self.dropped_attributes_count)
            if self.flags:
                proto_serializer.serialize_fixed32(b"5", self.flags)


class Status(MessageMarshaler):
    def __init__(
        self,
        message: str = "",
        code: int = 0,
    ):
        self.message: str = message
        self.code: int = code
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.message:
            size += util.size_string(b"\x12", self.message)
        if self.code:
            size += util.size_enum(b"\x18", self.code)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.message:
            proto_serializer.serialize_string(b"\x12", self.message)
        if self.code:
            proto_serializer.serialize_enum(b"\x18", self.code)

    class StatusCode(Enum):
        STATUS_CODE_UNSET = 0
        STATUS_CODE_OK = 1
        STATUS_CODE_ERROR = 2
