# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import (
    Any,
    Dict,
    List,
    Optional,
    TypedDict,
)

from snowflake.telemetry.serialize import (
    Enum,
    ProtoSerializer,
    util,
)


def AnyValue(
    bytes_value: Optional[bytes] = None,
    kvlist_value: Optional[bytes] = None,
    array_value: Optional[bytes] = None,
    double_value: Optional[float] = None,
    int_value: Optional[int] = None,
    bool_value: Optional[bool] = None,
    string_value: Optional[str] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    # oneof group value
    if bytes_value is not None:
        proto_serializer.serialize_bytes(b":", bytes_value)
    elif kvlist_value is not None:
        proto_serializer.serialize_message(b"2", kvlist_value)
    elif array_value is not None:
        proto_serializer.serialize_message(b"*", array_value)
    elif double_value is not None:
        proto_serializer.serialize_double(b"!", double_value)
    elif int_value is not None:
        proto_serializer.serialize_int64(b"\x18", int_value)
    elif bool_value is not None:
        proto_serializer.serialize_bool(b"\x10", bool_value)
    elif string_value is not None:
        proto_serializer.serialize_string(b"\n", string_value)
    return proto_serializer.out


def ArrayValue(
    values: Optional[List[bytes]] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if values:
        proto_serializer.serialize_repeated_message(b"\n", values)
    return proto_serializer.out


def KeyValueList(
    values: Optional[List[bytes]] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if values:
        proto_serializer.serialize_repeated_message(b"\n", values)
    return proto_serializer.out


def KeyValue(
    key: Optional[str] = None,
    value: Optional[bytes] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if key:
        proto_serializer.serialize_string(b"\n", key)
    if value:
        proto_serializer.serialize_message(b"\x12", value)
    return proto_serializer.out


def InstrumentationScope(
    name: Optional[str] = None,
    version: Optional[str] = None,
    attributes: Optional[List[bytes]] = None,
    dropped_attributes_count: Optional[int] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if name:
        proto_serializer.serialize_string(b"\n", name)
    if version:
        proto_serializer.serialize_string(b"\x12", version)
    if attributes:
        proto_serializer.serialize_repeated_message(b"\x1a", attributes)
    if dropped_attributes_count:
        proto_serializer.serialize_uint32(b" ", dropped_attributes_count)
    return proto_serializer.out
