# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class AnyValue(MessageMarshaler):
    def __init__(
        self,
        bytes_value: bytes = None,
        kvlist_value: MessageMarshaler = None,
        array_value: MessageMarshaler = None,
        double_value: float = None,
        int_value: int = None,
        bool_value: bool = None,
        string_value: str = None,
    ):
        self.bytes_value = bytes_value
        self.kvlist_value = kvlist_value
        self.array_value = array_value
        self.double_value = double_value
        self.int_value = int_value
        self.bool_value = bool_value
        self.string_value = string_value
        super().__init__(self.calculate_size())

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        # oneof group value
        if self.bytes_value is not None:
            proto_serializer.serialize_bytes(b":", self.bytes_value)
        elif self.kvlist_value is not None:
            proto_serializer.serialize_message(b"2", self.kvlist_value)
        elif self.array_value is not None:
            proto_serializer.serialize_message(b"*", self.array_value)
        elif self.double_value is not None:
            proto_serializer.serialize_double(b"!", self.double_value)
        elif self.int_value is not None:
            proto_serializer.serialize_int64(b"\x18", self.int_value)
        elif self.bool_value is not None:
            proto_serializer.serialize_bool(b"\x10", self.bool_value)
        elif self.string_value is not None:
            proto_serializer.serialize_string(b"\n", self.string_value)

    def calculate_size(self) -> int:
        size = 0
        if self.bytes_value is not None:
            size += util.size_bytes(b":", self.bytes_value)
        if self.kvlist_value is not None:
            size += util.size_message(b"2", self.kvlist_value)
        if self.array_value is not None:
            size += util.size_message(b"*", self.array_value)
        if self.double_value is not None:
            size += util.size_double(b"!", self.double_value)
        if self.int_value is not None:
            size += util.size_int64(b"\x18", self.int_value)
        if self.bool_value is not None:
            size += util.size_bool(b"\x10", self.bool_value)
        if self.string_value is not None:
            size += util.size_string(b"\n", self.string_value)
        return size


class ArrayValue(MessageMarshaler):
    def __init__(
        self,
        values: List[MessageMarshaler] = None,
    ):
        self.values = values
        super().__init__(self.calculate_size())

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.values:
            proto_serializer.serialize_repeated_message(b"\n", self.values)

    def calculate_size(self) -> int:
        size = 0
        if self.values:
            size += util.size_repeated_message(b"\n", self.values)
        return size


class KeyValueList(MessageMarshaler):
    def __init__(
        self,
        values: List[MessageMarshaler] = None,
    ):
        self.values = values
        super().__init__(self.calculate_size())

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.values:
            proto_serializer.serialize_repeated_message(b"\n", self.values)

    def calculate_size(self) -> int:
        size = 0
        if self.values:
            size += util.size_repeated_message(b"\n", self.values)
        return size


class KeyValue(MessageMarshaler):
    def __init__(
        self,
        key: str = "",
        value: MessageMarshaler = None,
    ):
        self.key = key
        self.value = value
        super().__init__(self.calculate_size())

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.key:
            proto_serializer.serialize_string(b"\n", self.key)
        if self.value:
            proto_serializer.serialize_message(b"\x12", self.value)

    def calculate_size(self) -> int:
        size = 0
        if self.key:
            size += util.size_string(b"\n", self.key)
        if self.value:
            size += util.size_message(b"\x12", self.value)
        return size


class InstrumentationScope(MessageMarshaler):
    def __init__(
        self,
        name: str = "",
        version: str = "",
        attributes: List[MessageMarshaler] = None,
        dropped_attributes_count: int = 0,
    ):
        self.name = name
        self.version = version
        self.attributes = attributes
        self.dropped_attributes_count = dropped_attributes_count
        super().__init__(self.calculate_size())

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.name:
            proto_serializer.serialize_string(b"\n", self.name)
        if self.version:
            proto_serializer.serialize_string(b"\x12", self.version)
        if self.attributes:
            proto_serializer.serialize_repeated_message(b"\x1a", self.attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b" ", self.dropped_attributes_count)

    def calculate_size(self) -> int:
        size = 0
        if self.name:
            size += util.size_string(b"\n", self.name)
        if self.version:
            size += util.size_string(b"\x12", self.version)
        if self.attributes:
            size += util.size_repeated_message(b"\x1a", self.attributes)
        if self.dropped_attributes_count:
            size += util.size_uint32(b" ", self.dropped_attributes_count)
        return size
