# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/resource/v1/resource.proto

from __future__ import annotations

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class Resource(MessageMarshaler):
    def __init__(
        self,
        attributes: List[KeyValue] = None,
        dropped_attributes_count: int = 0,
    ):
        self.attributes: List[KeyValue] = attributes
        self.dropped_attributes_count: int = dropped_attributes_count
        super().__init__()

    def calculate_size(self) -> int:
        size = 0
        if self.attributes:
            size += util.size_repeated_message(b"\n", self.attributes)
        if self.dropped_attributes_count:
            size += util.size_uint32(b"\x10", self.dropped_attributes_count)
        return size

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.attributes:
            proto_serializer.serialize_repeated_message(b"\n", self.attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"\x10", self.dropped_attributes_count)
