# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/resource/v1/resource.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
    util,
)


class Resource(MessageMarshaler):
    attributes: List["KeyValue"]
    dropped_attributes_count: int

    def __init__(
        self,
        attributes=None,
        dropped_attributes_count=0,
    ):
        self._attributes = attributes
        self.dropped_attributes_count = dropped_attributes_count

        __size = 0
        if attributes:
            __size += util.size_repeated_message(b"\n", attributes)
        if dropped_attributes_count:
            __size += util.size_uint32(b"\x10", dropped_attributes_count)
        super().__init__(__size)

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self._attributes:
            proto_serializer.serialize_repeated_message(b"\n", self._attributes)
        if self.dropped_attributes_count:
            proto_serializer.serialize_uint32(b"\x10", self.dropped_attributes_count)
